### ISSUE TITLE
개발 서버 배포

### ISSUE THREAD

**Issue by yyytir777** [Xpact-2025/BE#12]
## 📌 기능 개요
- 개발 서버 배포 진행
- main브랜치 push 및 pr 시 github actions으로 자동 배포
- docker로 이미지 생성
- EC2에 애플리케이션과 redis, nginx 실행 -> docker compose를 통한 배포

<img width="832" alt="Image" src="https://github.com/user-attachments/assets/a9230cc6-3d60-4de0-a18b-9995b2170931" />

## 📝작업 내용
- [x] EC2 생성 및 설정 (패키지 설치)
- [x] Dockerfile 작성
- [x] github workflow 작성
- [x] docker-compose.yaml 작성
- [x] .env 파일 설정

## 🤯 주요 사항
- 여러 서버를 패키징 처리할 것을 대비하여 dockerhub 대신 github에서 지원하는 github container registry(GHCR)사용 (500MB까지)
- docker build, pull, push를 dockerhub가 아닌 ghcr로 진행함
```yaml
      # Dokcer Login
      - name: Docker Login to GHCR
        run: echo ${{ secrets.WONJAE_GITHUB_PAT }} | docker login ghcr.io -u ${{ secrets.WONJAE_GITHUB_USERNAME }} --password-stdin

      # Image build ->  ghcr.io/<OWNER>/<REPO>:<TAG> .
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ secrets.ORG_NAME }}/xpact-api:latest .

      # docker container push
      - name: Push Docker Images
        run: docker push ghcr.io/${{ secrets.ORG_NAME }}/xpact-api:latest
```

- xpact-dev-instance 디렉토리
```
~/
├── docker-compose.yaml
├── xpact-api/
│   └── .env
└── nginx/
    └── nginx.conf
```
